os:
    - windows
    - linux
language: python
python:
    - '2.7'
    - '3.7'
matrix:
    allow_failures:
        - python: '3.7'
install:
    - pip install -e .
script:
    - echo HOORAY
    - test -L bCNC/bCNC.py
    - test -z $(find -name '*.pyc' -o -name '*.pyo')
    - python -t -m compileall -f bCNC
    - python setup.py sdist
