language: python
python:
    - '2.7'
    - '3.7'
matrix:
    allow_failures:
        - python: '3.7'
install:
    - pip install -e .
script:
    - echo HOORAY
    - python -m compileall bCNC
    - python setup.py sdist
