language: python
python:
    - '2.7'
    - '3.7'
matrix:
    allow_failures:
        - python: '3.7'
install:
    - pip install -e .
script:
    - echo HOORAY
    - test $(find -name '*.pyc' | wc -l) -eq 0
    - python -t -m compileall -f bCNC
    - python setup.py sdist
